name: test

on:
  push:
    branches:
      - "main"

jobs:
  install-dev-macos-arm64:
    name: "Verify dev env"
    runs-on: "macos-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-python@v5"
        with:
          python-version: "3.11"
      - name: "test stuff"
        run: |
          python -m pip install tables
